[package]
name = "doom-cli"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.3", features = ["derive", "env"] }
deser-hjson = "1.1.0"
dialoguer = "0.10.3"
serde = "1.0.152"
thiserror = "1.0.38"
walkdir = "2.3.2"

[features]
