[package]
name = "playdoom"
version = "0.1.0"
authors = ["kyle.coffey <kyle.coffey@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.33.3"
itertools = "0.10.0"
lazy_static = "1.4.0"
dirs = "3.0.1"
once_cell = "1.7.2"
walkdir = "2.3.2"
serde = { version = "1.0.125", features = ["derive"] }
toml = "0.5.8"
anyhow = "1.0.40"
ctrlc = "3.1.8"
dialoguer = "0.8.0"
path-clean = "0.1.0"
indoc = "1.0.3"
thiserror = "1.0.24"
pretty_env_logger = "0.4.0"
log = "0.4.14"
tokio = { version = "1.4.0", features = ["full"] }
indicatif = "0.15.0"
