[package]
name = "playdoom"
version = "0.1.0"
authors = ["kyle.coffey <kyle.coffey@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.33"
itertools = "0.10"
lazy_static = "1.4"
dirs = "3.0"
once_cell = "1.7"
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
anyhow = "1.0"
ctrlc = "3.1"
dialoguer = "0.8"
path-clean = "0.1"
indoc = "1.0"
thiserror = "1.0"
pretty_env_logger = "0.4"
log = "0.4"
