[package]
name = "playdoom"
version = "0.4.2"
authors = ["kyle.coffey <kyle.coffey@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.34.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
dirs = "4.0.0"
once_cell = "1.9.0"
walkdir = "2.3.2"
serde = { version = "1.0.132", features = ["derive"] }
anyhow = "1.0.51"
ctrlc = "3.2.1"
dialoguer = "0.9.0"
path-clean = "0.1.0"
indoc = "1.0.3"
thiserror = "1.0.30"
pretty_env_logger = "0.4.0"
log = "0.4.14"
tokio = { version = "1.15.0", features = ["full"] }
indicatif = "0.16.2"
ron = "0.7.0"
