[package]
name = "doom-cli"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.14", features = ["derive", "env"] }
deser-hjson = "1.0.2"
dialoguer = "0.9.0"
serde = "1.0.136"
thiserror = "1.0.30"
walkdir = "2.3.2"

[features]
